
modLoader = "javafml"
loaderVersion = "${loader_version_range}"

license = "${mod_license}"
issueTrackerURL = "${mod_github}/issues"

[[mods]]
    modId = "a_good_place"
    version = "${mod_version}"
    displayName = "${mod_name}"
    logoFile = "icon.png"
    authors = "${mod_authors}"
    credits = "${mod_credits}"
    description = '''${mod_description}'''
    modUrl = "${mod_homepage}"
    itemIcon="minecraft:brush" #catalogue icon

[[dependencies.a_good_place]]
    modId = "forge"
    mandatory = true
    versionRange = "${neo_version_range}"
    ordering = "NONE"
    side = "CLIENT"

[[dependencies.a_good_place]]
    modId = "minecraft"
    mandatory = true
    versionRange = "[${minecraft_min_version},${minecraft_max_version}]"
    ordering = "NONE"
    side = "CLIENT"

